"""Statistic added score replaced press_time by number of clicks

Revision ID: 0dc4a7545e5b
Revises: 860ad7f53dcf
Create Date: 2024-11-12 01:11:56.241374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0dc4a7545e5b'
down_revision: Union[str, None] = '860ad7f53dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('clicks_number', sa.Integer(), nullable=False))
    op.add_column('statistic', sa.Column('score', sa.Integer(), nullable=False))
    op.drop_column('statistic', 'average_key_press_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('average_key_press_time', mysql.FLOAT(), nullable=False))
    op.drop_column('statistic', 'score')
    op.drop_column('statistic', 'clicks_number')
    # ### end Alembic commands ###
