"""Task added keyboard zones

Revision ID: 1d6883dafa4a
Revises: 8b9e7fb770a4
Create Date: 2024-12-14 12:19:31.457505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6883dafa4a'
down_revision: Union[str, None] = '8b9e7fb770a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_zone',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('keyboardzone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyboardzone_id'], ['keyboardzone.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_zone')
    # ### end Alembic commands ###
