"""Add path to profile photo in User table

Revision ID: 860ad7f53dcf
Revises: b39b91942ffe
Create Date: 2024-11-11 10:25:16.585255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860ad7f53dcf'
down_revision: Union[str, None] = 'b39b91942ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_path', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_path')
    # ### end Alembic commands ###
