"""added clicks/min

Revision ID: 8b9e7fb770a4
Revises: 9a347c9be2ca
Create Date: 2024-12-02 11:50:45.470068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9e7fb770a4'
down_revision: Union[str, None] = '9a347c9be2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('clicks_per_minute', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'clicks_per_minute')
    # ### end Alembic commands ###
