"""Флаг успешности попытки в статистике

Revision ID: 9a347c9be2ca
Revises: 4530f38b59e2
Create Date: 2024-12-02 11:07:20.757059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a347c9be2ca'
down_revision: Union[str, None] = '4530f38b59e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('success', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'success')
    # ### end Alembic commands ###
