"""init

Revision ID: b39b91942ffe
Revises: 
Create Date: 2024-11-09 12:59:32.383911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39b91942ffe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=False),
    sa.Column('key_press_time', sa.Float(), nullable=False),
    sa.Column('max_mistakes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('keyboardzone',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('keys', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keys'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('status',
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('difficulty_zone',
    sa.Column('difficulty_id', sa.Integer(), nullable=True),
    sa.Column('keyboardzone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ),
    sa.ForeignKeyConstraint(['keyboardzone_id'], ['keyboardzone.id'], )
    )
    op.create_table('task',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('user',
    sa.Column('login', sa.String(length=10), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('statistic',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('used_time', sa.Float(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('average_key_press_time', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('difficulty_zone')
    op.drop_table('status')
    op.drop_table('keyboardzone')
    op.drop_table('difficulty')
    # ### end Alembic commands ###
